### ISSUE TITLE
Discount idle channels

### ISSUE THREAD

**Issue by C-Otto** [accumulator/charge-lnd#15]
Based on the assumption that a channel is not used because it is too expensive, it might help to reduce the fees for that channel. It'd be great to have this as a policy (possibly in addition to other policies?).

Channel X has fee rate 1000, but hasn't been used in 4 days. Reduce fee to 1000 - 0.9 * 4/30 (up to 90% discount for 30 days without forwardings).

I'm not sure if this should count consecutive days without forwardings, or just fractions (x out of the last y days).

**Comment by accumulator** [comment]
Interesting idea.. Should be doable while keeping charge-lnd stateless, if LND has all the necessary information.

**Comment by C-Otto** [comment]
I think you'd have to run something like `lncli fwdinghistory` and filter the results to see if the channel in question was used in an incoming transaction or earned fees for an outgoing transaction. I also think that circular (rebalancing) transactions should be ignored, as these do not originate from any remote peer.

NB: Caching the forwardings might improve performance significantly, but in theory you could just query every time you need the information.
