### ISSUE TITLE
Include a fee-change threshold for less updates

### ISSUE THREAD

**Issue by WeebDataHoarder** [accumulator/charge-lnd#18]
In routing nodes, many forwards can happen and this creates too many fee updates that take time to travel the network (which causes new forwards to fail due to different fee).

The current solution is to update fees less often, but this can have the issue of having your channels out of balance quicker.

A threshold (either in change percentage, or absolute sats change) could be taken into account. This would make changes only happen after the threshold has been reached after many channel forwards, and then issue a fee update. This would limit the micromanagement of fee rates, while still be able to check them quick and update when it is necessary.

**Comment by accumulator** [comment]
Yes something like that has been discussed in #13. Planning to generalize the PR so that it applies to all strategies, but it needs some refactoring for that.
