### ISSUE TITLE
Bug In Code? I don't know what else to title this

### ISSUE THREAD

**Issue by martinatime** [accumulator/charge-lnd#19]
I just installed this and ran the following
```
$charge-lnd --dry-run -c charge.config.example
<REDACTED CHANNEL INFO>
  policy:          proportional
  strategy:        proportional
  base_fee_msat:   1000
Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 6, in <module>
    from charge_lnd.charge_lnd import main
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd/charge_lnd.py", line 128, in <module>
    success = main()
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd/charge_lnd.py", line 83, in main
    print("  fee_ppm:         %s%s" % (fmt.col_hi(current_fee_ppm), s) )
UnicodeEncodeError: 'latin-1' codec can't encode character '\u279c' in position 35: ordinal not in range(256)
```

**Comment by accumulator** [comment]
Your system (or terminal) is not configured to use unicode characters. That's rare nowadays.

Quick fix is you can set the environment variable PYTHONIOENCODING to 'utf8' to override it for now (or configure your system to use UTF-8)

I'll add a check to handle this more gracefully in the code.

**Comment by accumulator** [comment]
fixed in a6f03ea31584bb59f32d103c05421edffe5f963a

**Comment by martinatime** [comment]
@accumulator You rock! I'll give it a try later today

**Comment by martinatime** [comment]
@accumulator It worked and looks awesome! I had to comment out the pool policy as it was throwing an error but everything else seemed to work out nice. Thanks again!
