### ISSUE TITLE
no warnings in the case of empty lines or comments in a file-list

### ISSUE THREAD

**Issue by steff123** [accumulator/charge-lnd#21]
Hello,
In the case of an empty line (espacially in the case of an empty file) or a commented line in a list of node-ids, the tool prints a warning that the pubkey is invalid. This should be suppressed.

Having a commented line would be helpful to descripe the node in the list.

Regards Steff

**Comment by accumulator** [comment]
Done.

d2c0b90140b5f86d13ccdb9ed183c4ae5ca48727
