### ISSUE TITLE
only set fee_ppm to the value of the peer

### ISSUE THREAD

**Issue by steff123** [accumulator/charge-lnd#22]
In case of a match_peer strategy one should be able to set fee_ppm to the value of the peer but to configure the base fee individually.

Regards Steff

**Comment by accumulator** [comment]
Yes good idea, I had thought of that but never implemented it.

You can now override either base_fee_msat or fee_ppm (or both, but that would be just a static policy)

498514954aee4f43ef523aa08c50e4f10712ed35
