### ISSUE TITLE
set max_htlc_msat as a ratio of the capacity

### ISSUE THREAD

**Issue by steff123** [accumulator/charge-lnd#23]
Hey,
in the case of a very low balance score I'd like to change the max_htlc_msat to a lower amount. But because of different channelsizes it is difficult to choose a fixed amount which fits for all channels.
Because of this one should be able to configure it as a ratio of the capacity, e.g. with implentation of a new parameter max_htlc_msat_ratio.

Regards Steff

**Comment by steff123** [comment]
Yes generalized expressions would be great. But I can imagine that you have to change the configuration format for this.

**Comment by thejerrod** [comment]
generalized expressions would be great, something like max_htlc_msat= capacity/2

**Comment by accumulator** [comment]
for now I've implemented this as a separate new property, `max_htlc_msat_ratio`.

05b142b71231e86dbe743f435d239c4243b1ed50
