### ISSUE TITLE
Feature Request: Continue Processing Strategy

### ISSUE THREAD

**Issue by martinatime** [accumulator/charge-lnd#24]
I'm not certain if this is possible so I'm just throwing this out there.
Currently there is an ignore strategy where if the criteria match the channel is exempted from the other blocks. But what if there was another strategy such that if the criteria matches then only will the other blocks be considered.
Here is a simple example but maybe I'm missing some nuances:
I have a config where there is an ignore block for excluding my "friend" nodes.
I have a second config only for my "friend" nodes.
In order to deal with the second case I would have to add the channel/node matching to each block in the second file as opposed to a single block at the top of the config that would exclude everyone that was not in my friends list.

**Comment by accumulator** [comment]
If you want to set a policy for friend nodes you should put them first (near the top) in the config file, so they don't match any other rules. The first matching policy is applied so currently this is the only way.

**Comment by martinatime** [comment]
I guess I was hoping that just as there is an ignore strategy there could be something like a "ignore those that don't match". This would be so that I could set up my base criteria at the top of a config and it would only consider nodes/channels that match the initial criteria for the rest of the config.

You are right that I can put policies at the top with my friends nodes but I would have to do that for every policy and it could be even more complex if I wanted even more "base" matching criteria over many policies.

I hope what I'm describing makes sense. Maybe it isn't technically feasible in the way the policies are parsed/interpreted.

**Comment by accumulator** [comment]
If I understand you correctly you expect the rules to act as a imperative programming language where you can define if-then-else blocks. It doesn't work that way, instead it works more like how e.g. Apache HTTPD works for URL request pattern matching, i.e. first match is final.

In your case, if you can negate the 'ignore those that don't match' predicate, you could put that on top of the config file and put an 'ignore' strategy on it.

**Comment by martinatime** [comment]
I think your last statement is exactly what I'm looking for. I don't need the if/then/else type of rules. I just need a way to ignore the whole world except what matches my criteria but instead of doing it in every policy block doing it once at the top of the file.

I didn't see a way to negate the matching criteria.

Based on the way this code currently works it is easy to say
Here is my friends list ignore them (or do something special, etc)

But it is impossible to say
Here is the world ignore all of it except for my friends list.

Maybe the misunderstanding is that I am trying to run this with different configuration files and I'm basically trying to target the configuration files to specific criteria. Maybe I'm being too ambitious and I just have to merge everything into a single file with a bunch of criteria in each policy/section

**Comment by accumulator** [comment]
> But it is impossible to say
> Here is the world ignore all of it except for my friends list.

Well that would be something like

```
[default]
s = ignore

[friends]
node.id = file:///friends
s = something 

```

**Comment by martinatime** [comment]
The latter example is what I am doing today. But let's say that the criteria would be more complex than a friends list then it would need to be duplicated as well.
This is kind of what I'm thinking
`
[filter]
node.id = file:///friends

[big friends]
chan.min_capacity = 5000

s=something

[active]
<some criteria>
s=something else

[default]
s=default strategy
`

**Comment by accumulator** [comment]
Can you try the `use_config` branch and tell me if this works for your use-case?

**Comment by martinatime** [comment]
I should definitely have some time in the next week to give it a try.

**Comment by martinatime** [comment]
This works GREAT!!!! It's a little different than what I was thinking but it matches my expectations perfectly.

I did notice one thing and I don't know if it was my configs or a bug but I had set up to use_config for a config_file that didn't exist yet and charge-lnd didn't complain but also seemed to not completely process everything.

I'll keep using this branch until it gets merged into the main branch. Let me know if you need anything tested. I'll update you if I find anything odd happening with the new strategy.

You rock! Also, if you want some inbound liquidity just PM me

**Comment by accumulator** [comment]
> I did notice one thing and I don't know if it was my configs or a bug but I had set up to use_config for a config_file that didn't exist yet and charge-lnd didn't complain but also seemed to not completely process everything.
> 
> I'll keep using this branch until it gets merged into the main branch. Let me know if you need anything tested. I'll update you if I find anything odd happening with the new strategy.

Thanks for the feedback. I think I'll keep the behaviour as it is now (ignore the matching channels if the config file is not found/is incorrect) but add a warning if something is up with the nested config.

> You rock! Also, if you want some inbound liquidity just PM me

:) thank you. Incoming liquidity is always welcome, my node URI is at the bottom of the README if you want to open a channel

**Comment by accumulator** [comment]
merged to master!
