### ISSUE TITLE
docker sample config

### ISSUE THREAD

**Issue by thefeli73** [accumulator/charge-lnd#33]
I (and a lot of others I imagine) would like to run charge-lnd in docker. However since I'm no docker expert and don't know how the docker image is set up i would like a sample config for running the container and a sample config for compose, so i can set up a config file and have the built in systemd service or cronjob or whatever inside the container take care of the rest.

**Comment by accumulator** [comment]
I've added a simple example to the README. Just plain `docker run` and no docker compose (as this container only needs a running LND instance, which you should already have running by using e.g. umbrel)
