### ISSUE TITLE
Bug while using verbose output and ignore strategy

### ISSUE THREAD

**Issue by martinatime** [accumulator/charge-lnd#34]
While using verbose output I am getting the following error/stacktrace
```
Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 6, in <module>
    from charge_lnd.charge_lnd import main
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd/charge_lnd.py", line 143, in <module>
    success = main()
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd/charge_lnd.py", line 92, in main
    if min_fee_ppm_delta > abs(new_fee_ppm - current_fee_ppm):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
The prior output is from a node that was in a file list of nodes with a strategy of ignore.

When I took the pubkey of a node above it in the output and added it to the file the error occurs that that node. So it seems to be an issue in the ignore strategy when verbose is on.

Everything seems to work fine when verbose is off.

**Comment by accumulator** [comment]
Ah, I think I found the issue. Can you test against latest master?

**Comment by martinatime** [comment]
I'll give it a try this evening

**Comment by martinatime** [comment]
Yep, it's working correctly now. Great job!
