### ISSUE TITLE
Issue installing on docker (Umbrel)

### ISSUE THREAD

**Issue by entreprenewer** [accumulator/charge-lnd#36]
Hey all..
STILL working on getting this going on Umbrel (it's been a long journey)

I have the charge-lnd.config file at ~/umbrel/apps/charge-lnd/charge-lnd.config

Here's the command I'm running:

```
docker run --rm -it --network=umbrel_main_network \
  -e GRPC_LOCATION=lnd:10009 \
  -e LND_DIR=/data/.lnd \
  -e CONFIG_LOCATION=/app/charge.config \
  -v /home/umbrel/umbrel/lnd:/data/.lnd \
  -v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config \
   accumulator/charge-lnd:latest
```

Here's the error I'm getting:
```Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 5, in <module>
    from charge_lnd.charge_lnd import main
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 143, in <module>
    success = main()
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 39, in main
    lnd = Lnd(arguments.lnddir, arguments.grpc)
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/lnd.py", line 33, in __init__
    self.feereport = self.get_feereport()
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/lnd.py", line 53, in get_feereport
    feereport = self.stub.FeeReport(ln.FeeReportRequest())
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1627373607.142962053","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5420,"referenced_errors":[{"created":"@1627373607.142946924","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>```

I'm a beginner at this stuff, so I hope someone can help me see where I've gone wrong.

**Comment by accumulator** [comment]
Other umbrel apps seem to use $LND_IP:$LND_GRPC_PORT as the LND service endpoint.
Can you check if these environment variables are defined?

**Comment by entreprenewer** [comment]
Thanks for the fast reply, I actually came to the same conclusion by reading a how-to that Bosworth wrote on BOS.
The documentation for how to install on docker here assumes a LOT of pre-existing knowledge, so I'm going to write a new post, and you can copy from it freely... total beginners need much more support!

Anyways, I got it working... now just need to see if the cronjob works. Thank you!

**Comment by jonathanalevi** [comment]
@accumulator here is the guide, I now have everything working properly.

https://community.getumbrel.com/t/guide-installing-charge-lnd-in-a-docker-to-automate-your-fee-policies/2187

Perhaps you can link to it, or copy/paste it here? I see some references to RaspiBlitz, but many more people are using Umbrel these days, so there should be _something_ for those folks.

**Comment by accumulator** [comment]
Thanks a lot! I will add your guide to the README (I copy/pasted the Raspiblitz guide also from somewhere on the web as I don't have either Raspiblitz nor Umbrel :)

**Comment by accumulator** [comment]
One important remark: I don't publish docker containers directly to github anymore. Instead, I upload them to Docker Hub

https://hub.docker.com/repository/docker/accumulator/charge-lnd

**Comment by accumulator** [comment]
One more remark, you don't need to manually get the LND IP from `~/umbrel/.env`, you can just use `$LND_IP` in place where you need it, as it's an environment variable set by umbrel.

**Comment by jonathanalevi** [comment]
I'm not 100% sure of how to update, i.e. where to modify the text and which steps to remove. 
Please feel free to modify it and post, and then I'll update mine based on yours.

**Comment by andrewj-cardin** [comment]
I worked through jonathanalevi's guide (https://yalls.org/articles/97d67df1-d721-417d-a6c0-11d793739be9:0965AC5E-56CD-4870-9041-E69616660E6F/0d395aab-d85d-4039-a5cc-682950e89a9d) for my own Umbrel node, and I got it to work (although, I don't know that the crontab job was every repeating the command every hour, I suspect not). Now, though, I am getting the following error upon running the docker:

Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 5, in <module>
    from charge_lnd.charge_lnd import main
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 146, in <module>
    success = main()
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 30, in main
    config = Config(arguments.config)
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/config.py", line 18, in __init__
    with open(config_file, "r") as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/charge.config'

Seems to not find the /app/charg.config. I'm not a developer... how do I fix this?

**Comment by accumulator** [comment]
@jonathanalevi 's guide contains some errors. Verify the docker command in the condensed guide here : https://github.com/accumulator/charge-lnd/blob/master/INSTALL.md
