### ISSUE TITLE
Inverse proportional strategy

### ISSUE THREAD

**Issue by ursus-caerulus** [accumulator/charge-lnd#37]
I was missing an inverse proportional setting as an addition to the encourage routing channels that have a high local balance.

Changing the ratio 
from
ratio = channel.local_balance/(channel.local_balance + channel.remote_balance)
to
ratio = channel.remote_balance/(channel.local_balance + channel.remote_balance)
has the desired effect

I was not succesfull in implementing a new strategy in strategy.py, but could not find the issue.

How can I suggest a new strategy? Simply adding one in strategy.py did not work

**Comment by accumulator** [comment]
You probably changed to code correctly, but forgot to `pip3 install` before testing (or using lib path override `PYTHONPATH=<path to source> ./charge-lnd.py`)

However, I don't really see reverse proportional to be a valid use case..

**Comment by ursus-caerulus** [comment]
Thanks, that worked. 
I would like to make the channel with most outgoing liquidity a bit cheaper than the others so that one gets routed (and balanced) first. With the current proportional setting channels with more local balance get higher fees (because of the 1-ratio in the code)

**Comment by accumulator** [comment]
I think you're misinterpreting the formula. A ratio of 1.0 will result in a fee of `min_fee_ppm`, as the `(1-ratio)*(max_fee_ppm-min_fee_ppm)` component will be zero.
