### ISSUE TITLE
Error on my Umbrel node

### ISSUE THREAD

**Issue by andrewj-cardin** [accumulator/charge-lnd#40]
I worked through jonathanalevi's guide (https://yalls.org/articles/97d67df1-d721-417d-a6c0-11d793739be9:0965AC5E-56CD-4870-9041-E69616660E6F/0d395aab-d85d-4039-a5cc-682950e89a9d) for my own Umbrel node, and I got it to work (although, I don't know that the crontab job was every repeating the command every hour, I suspect not). Now, though, I am getting the following error upon running the docker:

**Here is the command:**
docker run --rm -it --network=umbrel_main_network \
-e GRPC_LOCATION=LND.IP.ADDRESS.GOES.HERE:10009 \
-e LND_DIR=/data/.lnd \
-e CONFIG_LOCATION=/app/charge.config \
-v /home/umbrel/umbrel/lnd:/data/.lnd \
-v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config \
accumulator/charge-lnd:latest

**Here is the output**
Traceback (most recent call last):
File "/usr/local/bin/charge-lnd", line 5, in
from charge_lnd.charge_lnd import main
File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 146, in
success = main()
File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 30, in main
config = Config(arguments.config)
File "/usr/local/lib/python3.9/site-packages/charge_lnd/config.py", line 18, in init
with open(config_file, "r") as f:
IsADirectoryError: [Errno 21] Is a directory: '/app/charge.config'

Seems to not find the /app/charg.config. I'm not a developer... how do I fix this?

**Comment by dylnbrnt** [comment]
I am having the same issue after updating to latest Umbrel v0.4.0. "charge.config is a directory" in nano

**Comment by dylnbrnt** [comment]
try deleting charge.config from charge-lnd directory with

$ sudo rmdir charge.config

then recreate the config file 

$ sudo touch charge.config

you can then populate the config file from https://raw.githubusercontent.com/accumulator/charge-lnd/master/charge.config.example

**Comment by accumulator** [comment]
It's better to mount the entire folder instead of just the charge.config file into the container. So
`-v /home/umbrel/umbrel/apps/charge-lnd:/app
`instead of
`-v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config `

This way you can also use the `use_config` strategy

**Comment by andrewj-cardin** [comment]
> It's better to mount the entire folder instead of just the charge.config file into the container. So
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd:/app `
> 
> instead of
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config `
> 
> This way you can also use the `use_config` strategy

Thank you!

**Comment by andrewj-cardin** [comment]
> try deleting charge.config from charge-lnd directory with
> 
> $ sudo rmdir charge.config
> 
> then recreate the config file
> 
> $ sudo touch charge.config
> 
> you can then populate the config file from https://raw.githubusercontent.com/accumulator/charge-lnd/master/charge.config.example

Thank you!

**Comment by andrewj-cardin** [comment]
> try deleting charge.config from charge-lnd directory with
> 
> $ sudo rmdir charge.config
> 
> then recreate the config file
> 
> $ sudo touch charge.config
> 
> you can then populate the config file from https://raw.githubusercontent.com/accumulator/charge-lnd/master/charge.config.example

This seems to have worked. Thanks again.

**Comment by qecez** [comment]
> It's better to mount the entire folder instead of just the charge.config file into the container. So
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd:/app `
> 
> instead of
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config `
> 
> This way you can also use the `use_config` strategy

`-bash: -v: command not found`

**Comment by qecez** [comment]
> It's better to mount the entire folder instead of just the charge.config file into the container. So
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd:/app `
> 
> instead of
> 
> `-v /home/umbrel/umbrel/apps/charge-lnd/charge.config:/app/charge.config `
> 
> This way you can also use the `use_config` strategy

Don't you need to `docker run` before that?

Can you please list all the necessary commands since there's a lot of us in the same boat?
