### ISSUE TITLE
match_peer strategy does not make the base_fee

### ISSUE THREAD

**Issue by BhaagBoseDK** [accumulator/charge-lnd#42]
One of my peer MasterYoda has base_fee 199 sat and base_fee_rate 0
I have created special section to match the peer
However the strategy always reduced the base_fee to 0 instead of matching to 199 (and even if I manually reset to 199 in the next run it is replaced by 0).

The configuration file is

[9-static]
#Match to channels which keep high static fees
#MasterYoda

node.id = 033dee9c6a0afc40ffd8f27d68ef260f3e5e1c19e59c6f9bb607fb04c1d497a809

strategy = match_peer

To correct this for now I changed to

[9-static]
#Match to channels which keep high static fees
#MasterYoda

node.id = 033dee9c6a0afc40ffd8f27d68ef260f3e5e1c19e59c6f9bb607fb04c1d497a809

strategy = match_peer
base_fee_msat = 199_000

But this would not be good if the peer base fee changes in future (because I will remain at 199).

**Comment by accumulator** [comment]
Your base fee is probably set by a (non-final) policy above the 9-static policy.

**Comment by BhaagBoseDK** [comment]
yes but shouldn't match peer overwrite that?
what if my fee-rate was also set in "my defaults" - the non final policy. In which case the match-peer would be totally ineffective?

**Comment by BhaagBoseDK** [comment]
ok so I moved base_fee_msat from my defaults and instead added the value in all policies which was supposed to take that default value from my default.

now match peer works and sets both values.

**Comment by accumulator** [comment]
> yes but shouldn't match peer overwrite that?

The idea is that you can overwrite base_fee or fee_ppm by adding it to the match_peer policy, or a non-final policy before the match_peer policy. If you want the match_peer policy to use both values from the peer, you should put it near the top of the config file, so before any defaults are set

> what if my fee-rate was also set in "my defaults" - the non final policy. In which case the match-peer would be totally ineffective?

Correct, you can override both parameters, which is quite useless :)
