### ISSUE TITLE
Multiple Channels with same peer are treated separately

### ISSUE THREAD

**Issue by BhaagBoseDK** [accumulator/charge-lnd#43]
If you have multiple channels with the same peer, they are treated separately. However lnd protocol treats multiple channels as one for routing purposes and therefore uses the highest fees for any of the multiple channel.

Therefore you may end up in a situation where CH1 is 100% local and has fee setup to encourage routing and CH2 is 100% remote and has fees setup to discourage routing, both CH1 and CH2 end up with discourage routing because network graph would show high fees (for discourage routing) is applied.

Solution - treat the local + remote for all channels with same peer together and apply the same fees for all channels with same peer.

**Comment by accumulator** [comment]
Ouch, this is a nasty one. For fees this it makes sense to combine multiple channels, however one might still want to set min/max HTLC per-channel. Some strategies also use channel specific attributes to calculate the fees, these would also need to become multi-channel aware (e.g. what to do with match_peer or cost strategies)

**Comment by BhaagBoseDK** [comment]
in the policies there is nothing to select channel specific (may be except the cost strategies where cost of channel open is specific to the channel). Otherwise all policies are driven by node.
Nor can you set channel specific min/max HTLC. 

A simpler solution is consider the local balance = sum of all local balance with the peer, remote balance = sum of all remote balance with the peer

And then apply the policies as they come in the path.

If specific channel id is specified, you can apply settings specific to that channel id.

**Comment by BhaagBoseDK** [comment]
The workaround I have used is to create specific static policy for this node (which defeats the purpose of proportional policy) but for the time being that works.

**Comment by accumulator** [comment]
> in the policies there is nothing to select channel specific (may be except the cost strategies where cost of channel open is specific to the channel). Otherwise all policies are driven by node.
> Nor can you set channel specific min/max HTLC.

No, there are many channel specific elements. chan.* matching criteria, strategies using channel peer attributes etc. Also note that min/max HTLC is channel specific.

> A simpler solution is consider the local balance = sum of all local balance with the peer, remote balance = sum of all remote balance with the peer

Like I tried to explain above, it isn't that simple.

But I'll see what I can do to have a reasonable way to handle this edge case.

**Comment by lnd-routing** [comment]
We could use this feature as well. It seems fairly common for large routing nodes to have multiple channels with the same peer.

Perhaps a node.channel_count filter and a new multi_proportional strategy could be added. That way the new strategy could have limited matching criteria without losing any existing features for the others.

**Comment by lnd-routing** [comment]
We threw together a pre-processor to handle this situation.

It's a bit of a hack, but it works.

https://github.com/lnd-routing/charge-multi

**Comment by dmp1ce** [comment]
I'm also wondering if there can be a multi_proportional strategy which always considers all channel balances to the same peer regardless of matching criteria. I'm happy to test any PRs.

**Comment by dmp1ce** [comment]
#77 works for my needs. I'm mostly using proportional as the default rule.

**Comment by accumulator** [comment]
Closed by #77
