### ISSUE TITLE
Support for UpdateChanStatus

### ISSUE THREAD

**Issue by BhaagBoseDK** [accumulator/charge-lnd#44]
It would be great to have support for [updatechanstatus](https://api.lightning.community/#v2-router-updatechanstatus)

so to stop routing status can be set to Disable
to allow routing the status can be set to Enable.

This can be used with liquidity setting for example max.chan_ratio = 0.1, disbale channel.

Most people today use workaround to raise fees instead which has other issues.

**Comment by accumulator** [comment]
duplicate of #31
