### ISSUE TITLE
support for #9999BaseFee

### ISSUE THREAD

**Issue by BhaagBoseDK** [accumulator/charge-lnd#47]
First of all, thank you very much for this amazing tool. It is GodSend to manage fee and therefore routing efficiently and to achieve an efficient return on liquidity deployed.

Now, it is well known the network is choked today due to "TemporaryChannelFailures" which is mainly a result of channel with depleted liquidity coming up higher in the routing path and failing. This is akin to a driver who fails to move to the side when running out of fuel and therefore blocking the fast lane.

To resolve this and to not cause inconvenience to my peers routing through me, I have started using base fee as a switch
BaseFee = 0 when routing is on from my side -> peer
BaseFee = 9999_000 mSat when routing is off from my side -> peer if liquidity is depleted.

I do this by putting a stop routing policy very high in (after default and my default) as below
```

[1-stop_routing]
# if < 10% on local increase fees very high
chan.max_ratio = 0.1
strategy = static
base_fee_msat = 9999_000
fee_ppm = 0

```
The advantage of using base fee instead of fee rate is simply because
a) most explorers look for fee-rate, very high fee rate could impact the ranking or optics.
b) by using base fee simply as on-off switch it offers a predictability to the peers
c) by consistently using 9999 as base fee to signal routing off, it also starts establishing 9999 as a signal for routing off instead of a desire to claim a very high fee. i.e. it is a service to the network instead of charging very high fee. As you can see, there is no liquidity to charge that high fee anyway, the route will fail. 

If many nodes are adopting this strategy, soon we can see a reduction in temporary channel failures and the network will flow smoothly through paths which have liquidity.

Since charge-lnd is most used tool for fee management, if such a configuration can be introduced in SampleConfiguration then it will really encourage the network to adopt this. 

If you agree, I can create a pull request for your review in the sample configuration file.

**Comment by accumulator** [comment]
I'm not really convinced this is a good idea.

1) Using magic numbers to signal a condition is really an anti-pattern. I recall that a while back that there was a discussion of adding an indicator on the gossip level which channel direction was the preferred direction (can't find a link right now). I think this is a much better way to filter out unlikely-to-work routing segments.
2) It still doesn't have the intended result for most routing attempts (particularly mobile clients), as most pathfinding implementations don't optimize for cost, but instead make attempts on _any_ route that is below a % fee threshold (e.g. a 3% threshold would still attempt a 9999 base fee route when the ppm = 1 and the invoice amount is > ~334000

**Comment by accumulator** [comment]
Maybe the newly added 'disable' strategy is a better solution?

**Comment by BhaagBoseDK** [comment]
Yes disable is a much better and cleaner option. Link for that fix?

**Comment by accumulator** [comment]
> Link for that fix?

Just use the master branch.

**Comment by BhaagBoseDK** [comment]
yes - just checked, updated my installation, tested and works perfectly.
also updated plebnet wiki for lnd13 suggested policy (using disable instead of base rate fee 9999_000)
