### ISSUE TITLE
Wrong description in charge.config.example for zerobasefee-initiative

### ISSUE THREAD

**Issue by ziggie1984** [accumulator/charge-lnd#55]
In the Example the following is described:

[zerobasefee-initiative]
#set base_fee_msat default to 0 if peer sets zero base fees
chan.max_fee_ppm = 0
base_fee_msat = 0

But in my understanding, this looks for the fee_rate of the peer, so in my view the should be something like:

chan.max_base_fee = 0

The above would mean if the peer has a feerate of 0 I will adjust my base_fee to 0 which is highly unlikely to happen.

**Comment by accumulator** [comment]
thanks, fixed
