### ISSUE TITLE
Remote Node

### ISSUE THREAD

**Issue by STEMr42** [accumulator/charge-lnd#57]
Doesn't work as is on remote node (Voltage)? Is it possible to add flags for remote node? ex: --macaroon-path "" --tlscert-path "" --socket "".  Looks like macaroon and cert path are relying on local running instance of LND.

**Comment by accumulator** [comment]
Macaroon (and certificate) should be placed where (only) charge-lnd can read them, as they are your credentials for accessing your LND instance. I agree that it is a bit annoying you need to construct the directory structure for that. I might make this easier in the future.

Once you have the macaroon and cert in the correct place, you can specify the location of your remote LND service with the --grpc option.
