### ISSUE TITLE
chan.activity_period not working as expected

### ISSUE THREAD

**Issue by Quenos** [accumulator/charge-lnd#63]
Have the following policy:

[idle-channel-2d]
chan.activity_period = 2d
chan.max_htlcs_out = 0
strategy = static
base_fee_msat = 0
fee_ppm = 350

Still the channel that had outgoing liquidity just 3 hours ago changed the fee based on this policy

Raspi 4.0 32-bit

**Comment by accumulator** [comment]
Can't reproduce this issue myself, but leaving it open for now as I can't rule it out either.

**Comment by Quenos** [comment]
Just tried it again
And seems to work. So maybe I did something wrong.
Although a newly created channel was also changed based on the rule set above.

**Comment by accumulator** [comment]
Ok, thanks for letting me know.

> Although a newly created channel was also changed based on the rule set above.

I guess this is expected behaviour, as the channel had no forwards yet :)
But good catch, I think taking this into account would be an improvement.
