### ISSUE TITLE
Strategy based on the period of channel activity

### ISSUE THREAD

**Issue by SaftCPU** [accumulator/charge-lnd#65]
Channels often have only one flow direction.
For such channels, a strategy that increases or decreases fees based on activity could be useful.

Example:
[increase fee]
chan.activity_period = 1d
chan.max_htlcs_out = 3
strategy = increase
chan.current_fee = +0.1%

[decrease fee]
chan.activity_period = 1d
chan.max_htlcs_out = 1
strategy = decrease
chan.current_fee = -0.1%

**Comment by hoplaaa** [comment]
I agree with the idea.
A use case is searching for the balance between fee and channel activity. Too low fee and you loose potential profit; too high fee and you don't route anything.

To do that, either you start from high fee and reduce till you get some activity, then increase till the point you like, either you start from low fee and increase till there is not enough activity.

Activity condition seems to be already implemented, the only missing thing is a basic strategy :
```
Name : dynamic 
Description : Reduce or increase the fee step by step until target is reached.
Parameters : max_fee_ppm_delta,fee_ppm_target
```

Applying to :
https://github.com/accumulator/charge-lnd/blob/cbf6b1221409e260881415908582815a8ae7232a/examples/incentivise-low-flow.config#L15-L19

We would have : 
```
[low-out-flow]
chan,activityperiod = 7d
chan.max_htlcs_out = 1
strategy = dynamic  
target_fee_ppm = 100
max_fee_ppm_delta = 100
```


Every time charge-lnd is called another step to the target fee is applied.

**Comment by SaftCPU** [comment]
> To do that, either you start from high fee and reduce till you get some activity, then increase till the point you like, either you start from low fee and increase till there is not enough activity.

I agree with that too.

I don't understand why we need a target_fee_ppm parameter, since we don't yet know the optimal fee for our desired channel activity. For example, if we want 1 transaction per day, per channel, we would have:

```
[low-out-flow]
strategy = dynamic  
wanted_htlc_out = 1
wanted_activity_period = 1d
max_fee_percentage_delta = 10%
```
The script then has to figure out the optimal fee for each channel by decreasing or increasing the fee based on the channel's activity. Fees should be adjusted on a percentage basis. Otherwise our max_fee_ppm_delta is the smallest possible fee above zero.

**Comment by hoplaaa** [comment]
We have the same need. 

`target` is a bad name, the idea is to set some limits, maybe `limit_fee_ppm `, or we can reuse `min_fee_ppm `and `max_fee_ppm`? ).
`max_fee_ppm_delta ` is a bad name, the idea is to define an absolute step to use. That might be easier to develop. Anyway I'm fine with proportions too. Ideally we would have the choice.


My approach was to have 2 rules : 1 to decrease, 1 to increase. Equilibrium would be met if it is within the defined limits. It looks easier to develop and harder to manage, but might be useful for other need.
Your approach is to have 1 rule that implement everything for that need. That would be perfect as end user for that specific need. It might be harder to develop.

I'll let @accumulator have a look on it.

**Comment by accumulator** [comment]
> I agree with the above, however, if you had a time_delta that specifies how often an update can occur, then you would not have the issues you mention

The last-update property of a channel cannot reliably be taken/derived from lnd, at least that wasn't the case a few months ago when I last looked at it. The alternative is storing this value ourselves, but I wanted to avoid making charge-lnd stateful.
