### ISSUE TITLE
chan.id and reference to external file breaks in all formats tried so far

### ISSUE THREAD

**Issue by TrezorHannes** [accumulator/charge-lnd#67]
I'm trying to separate my channel segmentation into different files, with the goal to write into those dynamically.
I've been able to pull in 
`node.id = file:///home/lnd/.config/test.list`
with `test.list` formatting just as
```
039cbc938e8a9095b60114143cdb301ae4d4d9bd1dca96763a494880863ac66055,
02868e12f320073cad0c2959c42559fbcfd1aa326fcb943492ed7f02c9820aa399
```

When trying to apply similar logic to channel-IDs, none of the following worked:
`chan.id = file:///home/lnd/.config/test.list `
in the main file, formatting of the pulled `test.list` with short channel IDs
```
717384x1380x2,
721770x2518x4
```
breaking with the following error:
`Ignored: invalid channel id '717384x1380x2,' in 'file:///home/lnd/.config/test.list'`

or with long channel IDs
```
763135836514680834,
784400391425949697,
795851805125050369
```

breaks with the following errors
```
Error evaluating criteria for channel 710983x401x1 in policy '<charge_lnd.policy.Policy object at 0x7f9c9e3a2be0>', ignoring channel. (Error=invalid literal for int() with base 10: 'chan.id = file')
Ignored: invalid channel id '763135836514680834,784400391425949697,795851805125050369' in 'file:///home/lnd/.config/test.list'
```
The policy section pulling it looks like this:
```
[1-Lowest-Normal]
chan.id = file:///home/lnd/.config/test.list
#chan.min_ratio = 0.05
strategy = proportional
min_fee_ppm = 30
max_fee_ppm = 90
```

Perhaps I'm using the wrong channel format, but [lndmanage](https://github.com/bitromortac/lndmanage), lncli or [LNDg](https://github.com/cryptosharks131/lndg) which I'm using for exporting the long format.

Any way this is a bug, or I'm just using the wrong output for filtering the channel-ID?

**Comment by accumulator** [comment]
Using commas in the chan/node files is invalid. 

But good point, I think it's good to make a change to allow commas. I'll leave this bugreport open
