### ISSUE TITLE
No such file or directory: '~/.lnd/tls.cert'

### ISSUE THREAD

**Issue by steff123** [accumulator/charge-lnd#75]
After the update from 0.2.4 to 0.2.10 I had the following problem. I am using docker and hence I set --lnddir to a different location. But the tool was still looking for tls.cert in ~/.lnd/tls.cert and not in [lnddir]/tls.cert. Seems to be a little bug IMHO.

As workaround I set the parameter --tlscert too. Then the script run.

**Comment by accumulator** [comment]
AH thanks. It seems to be a change in behavior after #68 where for the docker container environment vars now take precedence over command line options
