### ISSUE TITLE
Docker container doesn't have permission to access macaroon

### ISSUE THREAD

**Issue by derekmiller** [accumulator/charge-lnd#76]
When running the docker container I'm getting `PermissionError: [Errno 13] Permission denied: '/home/charge/.lnd/data/chain/bitcoin/mainnet/charge-lnd.macaroon'`. I think the Dockerfile may need to `chown` it or maybe there is another way to give it access?

**Comment by accumulator** [comment]
This is not the responsibility of the container. You should make the macaroon available to the container by giving read-access to the container userid (root)
