### ISSUE TITLE
Add error reporting for UpdateChannelPolicy

### ISSUE THREAD

**Issue by derlade** [accumulator/charge-lnd#83]
When running charge-lnd manually or from crontab, the channel properties are not updated according to the current configuration file. Instead they remain in their current state, although the output suggests that some properties are due for updating (i.e. fee_ppm 100 -> 10). Running charge-lnd repeatedly yields the same update output (i.e. fee_ppm 100 -> 10 for the same channel), and utilities like lntop show the channel still remaining at fee_ppm=100. 

Running lnd v0.15.0-beta and charge-lnd v0.2.12.

**Comment by accumulator** [comment]
Can you give a bit more context? 
Did it work correctly with lnd v0.14.x? 
Did it work with older charge-lnd? 
Is it a certain strategy that is problematic?
What authorizations are in the macaroon file you use?

**Comment by derlade** [comment]
Unfortunately, I cannot remember exactly for how long the issue persisted. IIRC, it must have been a few months at least and I simply ignored it at first, so at least since charge-lnd v0.12.2 and some version of v0.14.x.
It must have worked partially at some point in the past, since some channels are updated according to a previous version of the configuration file. Also, new channels I opened recently got updated to the current configuration; it seems as though older channels do not get updated properly. Furthermore, there is no specific strategy that is problematic; for instance, `max_htlc_msat` is not updated regardless of the strategy (be it either static, cost or match_peer). 
As for the macaroon file, it has `info:read`, `offchain:read`, `offchain:write` and `onchain:read` as permissions and is of version 2.

**Comment by derlade** [comment]
Actually, I'm not sure if it's a lnd issue. Calling updatechanpolicy manually with the same parameters reveals the following output:

```
{
        "failed_updates": [
                {
                        "outpoint": "XXX:1",
                        "reason": "UPDATE_FAILURE_INVALID_PARAMETER",
                        "update_error": "max htlc size of 500000000 mSAT is above max pending amount of 495000000 mSAT"
                }
        ]
}

```

So it seems that the error doesn't get passed downstream correctly, at least the charge-lnd output doesn't reveal any errors. Changing `max_htlc_msat` to `max_htlc_msat_ratio` in the config solved the problem.

**Comment by accumulator** [comment]
Ah, yes. charge-lnd is using a bit older `.proto` interface definitions, where error responses are not yet added. 
I will update these, and add error checking and reporting, once I have some time.
