### ISSUE TITLE
Non-final policies don't update max_htlc_msat_ratio

### ISSUE THREAD

**Issue by TrezorHannes** [accumulator/charge-lnd#89]
Hello there,

## Context 
I have a bunch of channels in the **ignore-strategy**, since I'm trying LNDg Autofee with those instead.

## Objective
I'd like to add `chan.min_ratio = 0.10` to the **ignore-strategy**, to allow my _stop-routing and discourage routing_ HTLC policies to kick in for those, too.

## Problem Statement
Once those channels are coming back and have more than 10% outbound, they fall back into the **ignore-policy**. But this policy cannot update `max_htlc_msat_ratio`. Hence, as soon those ignored_channels are balanced, my local_htlc_max is way to small from the earlier discourage-routing updates.

## Identified Solution
I have a default policy right in the beginning, but somehow, setting `max_htlc_msat_ratio = 0.94` isn't applied, even though the below should be applicable for all my channels, since there are no filtering conditions and no strategy (hence categorised as Non-final policy) and it's the second policy after [default].
```
[mydefaults]
# no strategy, so this only sets some defaults
# min_fee_ppm_delta = 20
time_lock_delta = 144
min_htlc_msat = 1_000
max_htlc_msat_ratio = 0.94
base_fee_msat = 1_000
```
I _think_ `time_lock_delta = 144` is also not applied.

## Question
Is it working as intended, that [non-final-policies](https://github.com/accumulator/charge-lnd#non-final-policies) only applies a subset of the following properties, or is this a bug?

  - base_fee_msat 
  - min_htlc_msat 
  - max_htlc_msat
  - max_htlc_msat_ratio
  - time_lock_delta
  - min_fee_ppm_delta

## Log Entry 
for a Channel with 42% on my side, where `max_htlc_msat` should be 2,970,000,000
```
lnd@debian-nuc:~$ charge --dry-run -v | grep LN.SIDESHIFT.AI -A 8
712292x1184x4 [LN.SIDESHIFT.AI|02459b759a62bc3ebfe98a320da237944cc4f35456384bd8fdefa7d0340c75f46f]
  policy:          ignored_channels
  strategy:        ignore
  channel status:  enabled
  base_fee_msat:   1000
  fee_ppm:         555
  min_htlc_msat:   1000
  max_htlc_msat:   2970000
  time_lock_delta: 144
```

**Comment by accumulator** [comment]
> Is it working as intended, that [non-final-policies](https://github.com/accumulator/charge-lnd#non-final-policies) only applies a subset of the following properties, or is this a bug?

It is working as intended. The non-final policies just apply default values, which only get applied by a final policy if the final policy doesn't override these defaults.

The ignore strategy is really ignoring the channel completely, i.e. none of the attributes are applied, even when matched by a non-final policy.

To allow charge-lnd to co-exist with LNDg, I think there should be something like a ignore-fees strategy, that only applies the min|max htlc and tld attributes.

**Comment by accumulator** [comment]
I think I got it done, but haven't tested it yet because I'm waiting for my bitcoind to re-index all blocks due to some data corruption.

You can test yourself if you want, see https://github.com/accumulator/charge-lnd/tree/ignore_fees_strategy

**Comment by TrezorHannes** [comment]
Affirmative, tested with a number of channels, and both `time_lock_delta` setting, and `max_htlc_msat` works, while the fee remains untouched / unchanged.

### Log entry
```
761528x1578x2 [bfx-lnd1|03cde60a6323f7122d5178255766e38114b4722ede08f7c9e0c5df9b912cc201d6]
  policy:          LNDg
  strategy:        ignore_fees
  min_htlc_msat:   1000
  max_htlc_msat:   14850000000 ➜ 14404500000
  time_lock_delta: 44 ➜ 99
```

Thank you so much, this is excellent!

**Comment by accumulator** [comment]
Thanks for your detailed problem report and testing feedback!
