### ISSUE TITLE
Can't run pip install

### ISSUE THREAD

**Issue by pfergi42** [accumulator/charge-lnd#93]
When I run this command

`pip install -U setuptools && pip install -r requirements.txt .`

I get an error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
.
.
.
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)
```

**Comment by pfergi42** [comment]
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)

**Comment by pfergi42** [comment]
Could be related to this?

https://github.com/pypa/setuptools/issues/3772

**Comment by accumulator** [comment]
Thanks for reporting.

As a temporary workaround, you could try keeping with an older `setuptools`

`pip install setuptools==65.7.0`

**Comment by pfergi42** [comment]
Thanks! That helped.
