### ISSUE TITLE
HTLC changes not applied

### ISSUE THREAD

**Issue by kroese** [accumulator/charge-lnd#94]
When I have a script like this:

```
[default]
# 'default' is special, it is used if no other policy matches a channel
strategy = static
base_fee_msat = 0
min_htlc_msat = 1000
max_htlc_msat_ratio = 1

[mydefaults]
# no strategy, so this only sets some defaults
min_fee_ppm_delta = 10

[low-local-balance]
chan.max_ratio = 0.05
strategy = static
min_htlc_msat = 0
max_htlc_msat_ratio = 0.000000000001
```

to set max htlc to zero when there is low local balance. 

I see charge-lnd reporting to make the changes to min and max htlc:

 ```
[Channel]
  policy:          low-local-balance
  strategy:        static
  min_htlc_msat:   1000 ➜ 0
  max_htlc_msat:   4950000000 ➜ 0
```

But these changes don't seem to effectuate at all. When I run charge-lnd again, it keeps making the same changes and when viewing the channel info in lnd-cli, thunderhub, etc. i can see that the max_htlc did not change. 

So is there a reason why these don't get applied?

**Comment by accumulator** [comment]
`charge-lnd` tries to apply, but `lnd` silently ignores min_htlc_msat=0 and max_htlc_msat=0

**Comment by stonedbear** [comment]
Can confirm facing same issue, it crops up randomly only on some channels. What eventually works is to close the channel and to open it again.

**Comment by accumulator** [comment]
Closing this, as it's primarily a LND issue
