### ISSUE TITLE
Charge LND causes systemd error

### ISSUE THREAD

**Issue by kroese** [accumulator/charge-lnd#96]
I have charge-lnd running as a hourly cronjob. And since recently I get this error on the docker host around the same time the container starts:

`systemd-networkd[553]: veth50ddba7: Failed to manage SR-IOV PF and VF ports, ignoring: Invalid argument`

I think it started after upgrading to Ubuntu 23.04. 

Also the message seems harmless, because charge-lnd is working like expected. But as I get email notifications for every error that happens on my system, it starts to get really annoying.

I tried looking at the code to figure out what makes it possibly cause this error, but I dont see it doing any strange network code. 

So it is also possible that error is a bug in Docker itself, and not in charge-lnd. Most of my other containers are running 24/7 and charge-lnd is the only one that gets started/stopped every hour. And the error occurs only 1 or 2 times each day, so it's very hard to pinpoint exactly why it occurs.

**Comment by accumulator** [comment]
> Nevermind, decided to report this issue directly to Docker instead: [moby/moby#45480](https://github.com/moby/moby/issues/45480) because possibly its not related to this containers code at all.

Yes, this is not related to charge-lnd. The error you are seeing indicates a hardware/driver compatibility issue with systemd-networkd
